### ISSUE TITLE
Unable to use the package giving error

### ISSUE THREAD

**Issue by Aniket8195** [altafc22/csc_picker#89]
E/flutter ( 3782): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Unable to load asset: "packages/csc_picker/lib/assets/country.json".
E/flutter ( 3782): The asset does not exist or has empty data.
E/flutter ( 3782): #0      PlatformAssetBundle.load.<anonymous closure> (package:flutter/src/services/asset_bundle.dart:327:9)
E/flutter ( 3782): <asynchronous suspension>
E/flutter ( 3782): #1      AssetBundle.loadString (package:flutter/src/services/asset_bundle.dart:92:27)
E/flutter ( 3782): <asynchronous suspension>
E/flutter ( 3782): #2      CSCPickerState.getResponse (package:csc_picker/csc_picker.dart:634:15)
E/flutter ( 3782): <asynchronous suspension>
E/flutter ( 3782): #3      CSCPickerState.getCountries (package:csc_picker/csc_picker.dart:642:21)
E/flutter ( 3782): <asynchronous suspension>

CSCPicker(
                          key:  _cscPickerKey,
                        onCountryChanged: (value) {
                          setState(() {
                            countryValue = value;
                          });
                        },
                        onStateChanged: (value) {
                          setState(() {
                            stateValue = value;
                          });
                        },
                        onCityChanged: (value) {
                          setState(() {
                            cityValue = value;
                          });
                        },
                        defaultCountry: CscCountry.India,
                        flagState: CountryFlag.DISABLE,
                        disableCountry: true,
                        layout: Layout.vertical,
                        //defaultCity: cityValue,
                        // defaultState: stateValue,
                        showStates: true,
                        showCities: true,
                      //  flagState: CountryFlag.SHOW_IN_DROP_DOWN_ONLY,
                        dropdownDecoration: BoxDecoration(
                          borderRadius: const BorderRadius.all(Radius.circular(8)),
                          border: Border.all(color: AppPallete.secondaryColor, width: 1),
                        ),
                        disabledDropdownDecoration: BoxDecoration(
                          borderRadius: const BorderRadius.all(Radius.circular(8)),
                          border: Border.all(color: AppPallete.secondaryColor, width: 1),
                        ),
                        selectedItemStyle: TextStyle(
                          color: AppPallete.secondaryColor,
                          fontSize: 14,
                        ),
                        dropdownHeadingStyle: TextStyle(
                          color: AppPallete.secondaryColor,
                          fontSize: 17,
                          fontWeight: FontWeight.bold,
                        ),
                        dropdownItemStyle: TextStyle(
                          color: AppPallete.secondaryColor,
                          fontSize: 14,
                        ),
                      ),

**Comment by Aniket8195** [comment]
Done , working now
